"""empty message

Revision ID: 37b9e9edba0d
Revises: 35dc8f36f698
Create Date: 2022-11-04 00:15:13.504437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37b9e9edba0d'
down_revision = '35dc8f36f698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articulo', 'pedidos',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articulo', 'pedidos',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
