"""empty message

Revision ID: 5d60c7564d86
Revises: 118934c15f17
Create Date: 2022-10-27 20:39:06.232986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d60c7564d86'
down_revision = '118934c15f17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_apellido_key', 'users', type_='unique')
    op.drop_constraint('users_nombre_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_nombre_key', 'users', ['nombre'])
    op.create_unique_constraint('users_apellido_key', 'users', ['apellido'])
    # ### end Alembic commands ###
